appIcon=harbour-whisperfish
x-nemo-icon=harbour-whisperfish
urgency=0
x-nemo-preview-icon=/usr/share/harbour-whisperfish/icons/blue.png
x-nemo-user-removable=true
x-nemo-feedback=
x-nemo-display-on=false
x-nemo-priority=10
x-nemo-led-disabled-without-body-and-summary=false
